作業目標

熟悉陣列維度轉換，並且會擷取需要資料

作業重點

使用reshap須注意order用法

where可以運用邏輯條件擷取資料

題目：
array1 = np.array(range(30))

1.將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

2.呈上題的 array，找出被 6 除餘 1 的數的索引

In [1]:
import numpy as np

In [5]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30), order='F')
a=array1.reshape((5,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [25]:
#2.呈上題的array，找出被6除餘1的數的索引
b=np.where(a%6==1)
b

(array([0, 1, 2, 3, 4]), array([1, 1, 1, 1, 1]))

In [ ]:
#得出(array([0, 1, 2, 3, 4]), 
      #array([1, 1, 1, 1, 1]))
#上面的回傳值代表 [0, 1], [1, 1], [2, 1], [3, 1], [4, 1] 均為符合條件的元素索引值。