作業目標

熟悉陣列維度轉換，並且會擷取需要資料

作業重點

使用reshap須注意order用法

where可以運用邏輯條件擷取資料

題目：
array1 = np.array(range(30))

1.將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

2.呈上題的 array，找出被 6 除餘 1 的數的索引

In [1]:
import numpy as np

In [26]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
a=array1.reshape((5,6), order='F')
a

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [28]:
#2.呈上題的array，找出被6除餘1的數的索引
b=np.where(a%6==1)
b

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))

In [ ]:
#得出(array([0, 1, 2, 3, 4]),
      #array([5, 0, 1, 2, 3]))
#上面的回傳值代表 [0, 5], [1, 0], [2, 1], [3, 2], [4, 3] 均為符合條件的元素索引值。